import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Footer from "@/layouts/footer";

const inter = Quicksand({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "SYNECX AI LABS",
  description: "Generated by create next app",
  icons: {
    icon: "/aihand.svg", // path to your favicon
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} scroll-smooth>
        
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
